apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.ctrlserver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "backend.ctrlserver.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "backend.chart" . }}
spec:
  ports:
  - port: 8080
    targetPort: ctrl-port
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "backend.ctrlserver.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
