nameOverride: ""
fullnameOverride: ""

replicaCount: 1

serviceAccount:
  secretName: beneath-sa-key
  fileName: key.json 

image:
  pullPolicy: IfNotPresent
  repository: gcr.io/beneath/taskqueue
  tag: latest

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

env:
- name: ENV
  value: production
- name: BENEATH_CONTROL_REDIS_URL
  value: "redis://10.255.145.163/"
- name: BENEATH_CONTROL_POSTGRES_HOST
  value: "10.38.208.3"
- name: BENEATH_CONTROL_POSTGRES_DB
  value: "postgres"
- name: BENEATH_CONTROL_POSTGRES_USER
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: pg-user
- name: BENEATH_CONTROL_POSTGRES_PASSWORD
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: pg-password
- name: BENEATH_CONTROL_STRIPE_SECRET
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: stripe-secret-key      
- name: BENEATH_CONTROL_PAYMENTS_DRIVERS
  value: "anarchism,stripecard,stripewire"
- name: BENEATH_ENGINE_MQ_DRIVER
  value: "pubsub"
- name: BENEATH_ENGINE_LOOKUP_DRIVER
  value: "bigtable"
- name: BENEATH_ENGINE_WAREHOUSE_DRIVER
  value: "bigquery"
- name: BENEATH_ENGINE_BIGQUERY_PROJECT_ID
  value: "beneath"
- name: BENEATH_ENGINE_BIGQUERY_INSTANCES_DATASET_ID
  value: "instances"
- name: BENEATH_ENGINE_BIGTABLE_PROJECT_ID
  value: "beneath"
- name: BENEATH_ENGINE_BIGTABLE_INSTANCE_ID
  value: "beneath-bigtable-1"
- name: BENEATH_ENGINE_PUBSUB_PROJECT_ID
  value: "beneath"
- name: BENEATH_ENGINE_PUBSUB_SUBSCRIBER_ID
  value: "taskqueue"
- name: BENEATH_ENGINE_PUBSUB_TOPIC_PREFIX
  value: "beneath"
- name: BENEATH_ENGINE_PUBSUB_SUBSCRIPTION_PREFIX
  value: "beneath"
