stages:
  - build
  - deploy

.build:
  stage: build
  image: docker:stable
  services:
  - docker:dind
  before_script:
  - docker login -u _json_key -p "${GCR_SERVICE_KEY}" https://gcr.io
  when: manual
  only:
    - stable

build:frontend:
  extends: .build
  variables:
    IMAGE: gcr.io/beneath/frontend
  script: 
    - docker pull ${IMAGE}:latest || true
    - docker build -f ./build/web/Dockerfile -t ${IMAGE}:latest -t ${IMAGE}:${CI_COMMIT_SHORT_SHA} --cache-from ${IMAGE}:latest ./web
    - docker push ${IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${IMAGE}:latest

.build:go:
  script: 
    - docker pull ${IMAGE}:builder || true
    - docker build -f ./build/${CMD_NAME}/Dockerfile --target builder -t ${IMAGE}:builder --cache-from ${IMAGE}:builder .
    - docker build -f ./build/${CMD_NAME}/Dockerfile -t ${IMAGE}:latest -t ${IMAGE}:${CI_COMMIT_SHORT_SHA} --cache-from ${IMAGE}:builder .
    - docker push ${IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${IMAGE}:latest
    - docker push ${IMAGE}:builder

build:control:
  extends:
  - .build
  - .build:go
  variables:
    CMD_NAME: control
    IMAGE: gcr.io/beneath/${CMD_NAME}

build:gateway:
  extends:
  - .build
  - .build:go
  variables:
    CMD_NAME: gateway
    IMAGE: gcr.io/beneath/${CMD_NAME}

build:pipeline:
  extends:
  - .build
  - .build:go
  variables:
    CMD_NAME: pipeline
    IMAGE: gcr.io/beneath/${CMD_NAME}

build:taskqueue:
  extends:
  - .build
  - .build:go
  variables:
    CMD_NAME: taskqueue
    IMAGE: gcr.io/beneath/${CMD_NAME}

.deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.2.1
  only:
    - stable
  script:
    - helm upgrade --install --wait --force ${CMD_NAME} deployments/helm/${CMD_NAME}/ --set image.tag=${CI_COMMIT_SHORT_SHA} --set replicaCount=${REPLICAS} --namespace=${KUBE_NAMESPACE}

.deploy:prod:
  variables:
    KUBE_NAMESPACE: production
  environment:
    name: production
    url: https://beneath.dev

deploy:frontend:
  extends:
  - .deploy
  - .deploy:prod
  needs: ["build:frontend"]
  variables:
    CMD_NAME: frontend
    REPLICAS: ${REPLICAS_FRONTEND}
    REPLICAS_FRONTEND: 2

deploy:control:
  extends:
  - .deploy
  - .deploy:prod
  needs: ["build:control"]
  variables:
    CMD_NAME: control
    REPLICAS: ${REPLICAS_CONTROL}
    REPLICAS_CONTROL: 2

deploy:gateway:
  extends:
  - .deploy
  - .deploy:prod
  needs: ["build:gateway"]
  variables:
    CMD_NAME: gateway
    REPLICAS: ${REPLICAS_GATEWAY}
    REPLICAS_GATEWAY: 2

deploy:pipeline:
  extends:
  - .deploy
  - .deploy:prod
  needs: ["build:pipeline"]
  variables:
    CMD_NAME: pipeline
    REPLICAS: ${REPLICAS_PIPELINE}
    REPLICAS_PIPELINE: 1

deploy:taskqueue:
  extends:
  - .deploy
  - .deploy:prod
  needs: ["build:taskqueue"]
  variables:
    CMD_NAME: taskqueue
    REPLICAS: ${REPLICAS_TASKQUEUE}
    REPLICAS_TASKQUEUE: 1
