nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: gcr.io/beneath/ee-web
  tag: latest

ingress:
  hosts: []

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

extraEnv: []
