apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "gateway.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: {{ .Values.serviceAccount.secretName }}
        secret:
          secretName: {{ .Values.serviceAccount.secretName }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: gw-port
          containerPort: 8080
        - name: gw-grpc-port
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /healthz
            port: gw-port
        readinessProbe:
          httpGet:
            path: /healthz
            port: gw-port
        volumeMounts:
        - name: {{ .Values.serviceAccount.secretName }}
          mountPath: /var/secrets/google
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/{{ .Values.serviceAccount.fileName }}
        {{- toYaml .Values.env | nindent 8 }}
