nameOverride: ""
fullnameOverride: ""

replicaCount: 1

serviceAccount:
  secretName: beneath-sa-key
  fileName: key.json 

image:
  pullPolicy: IfNotPresent
  repository: gcr.io/beneath/control
  tag: latest

ingress:
  host: control.beneath.dev

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

env:
- name: ENV
  value: production
- name: BENEATH_FRONTEND_HOST
  value: "https://beneath.dev"
- name: BENEATH_CONTROL_PORT
  value: "8080"
- name: BENEATH_CONTROL_HOST
  value: "https://control.beneath.dev"
- name: BENEATH_CONTROL_REDIS_URL
  value: "redis://10.255.145.163/"
- name: BENEATH_CONTROL_POSTGRES_HOST
  value: "10.38.208.3"
- name: BENEATH_CONTROL_POSTGRES_DB
  value: "postgres"
- name: BENEATH_CONTROL_POSTGRES_USER
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: pg-user
- name: BENEATH_CONTROL_POSTGRES_PASSWORD
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: pg-password
- name: BENEATH_CONTROL_SESSION_SECRET
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: session-secret
- name: BENEATH_CONTROL_STRIPE_SECRET
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: stripe-secret-key      
- name: BENEATH_CONTROL_GITHUB_AUTH_ID
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: github-auth-id
- name: BENEATH_CONTROL_GITHUB_AUTH_SECRET
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: github-auth-secret
- name: BENEATH_CONTROL_GOOGLE_AUTH_ID
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: google-auth-id
- name: BENEATH_CONTROL_GOOGLE_AUTH_SECRET
  valueFrom:
    secretKeyRef:
      name: beneath-secrets
      key: google-auth-secret
- name: BENEATH_CONTROL_PAYMENTS_DRIVERS
  value: "anarchism,stripecard,stripewire"
- name: BENEATH_ENGINE_MQ_DRIVER
  value: "pubsub"
- name: BENEATH_ENGINE_LOOKUP_DRIVER
  value: "bigtable"
- name: BENEATH_ENGINE_WAREHOUSE_DRIVER
  value: "bigquery"
- name: BENEATH_ENGINE_BIGQUERY_PROJECT_ID
  value: "beneath"
- name: BENEATH_ENGINE_BIGTABLE_PROJECT_ID
  value: "beneath"
- name: BENEATH_ENGINE_BIGTABLE_INSTANCE_ID
  value: "beneath-bigtable-1"
- name: BENEATH_ENGINE_PUBSUB_PROJECT_ID
  value: "beneath"
- name: BENEATH_ENGINE_PUBSUB_SUBSCRIBER_ID
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: BENEATH_ENGINE_PUBSUB_TOPIC_PREFIX
  value: "beneath"
- name: BENEATH_ENGINE_PUBSUB_SUBSCRIPTION_PREFIX
  value: "beneath"
