apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock-1m
  labels:
    app.kubernetes.io/name: clock-1m
    app.kubernetes.io/instance: clock-1m
    app.kubernetes.io/managed-by: Manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clock-1m
      app.kubernetes.io/instance: clock-1m
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clock-1m
        app.kubernetes.io/instance: clock-1m
    spec:
      containers:
      - name: clock-1m
        image: gcr.io/beneath/clock-1m:latest
        imagePullPolicy: Always
        env:
        - name: BENEATH_SECRET
          valueFrom:
            secretKeyRef:
              name: clock-1m
              key: secret
