mq:
  driver: "" # env: BENEATH_MQ_DRIVER

control:
  port: 4000 # env: BENEATH_CONTROL_PORT
  host: "http://localhost:4000" # env: BENEATH_CONTROL_HOST
  frontend_host: "http://localhost:3000" # env: BENEATH_CONTROL_FRONTEND_HOST

  redis:
    url: "redis://localhost/" # env: BENEATH_CONTROL_REDIS_URL

  postgres:
    host: "localhost" # env: BENEATH_CONTROL_POSTGRES_HOST
    database: "postgres" # env: BENEATH_CONTROL_POSTGRES_DB
    user: "postgres" # env: BENEATH_CONTROL_POSTGRES_USER
    password: "" # env: BENEATH_CONTROL_POSTGRES_PASSWORD

  session_secret: "" # env: BENEATH_CONTROL_SESSION_SECRET
  auth:
    github:
      id: "" # env: BENEATH_CONTROL_AUTH_GITHUB_ID
      secret: "" # env: BENEATH_CONTROL_AUTH_GITHUB_SECRET
    google:
      id: "" # env: BENEATH_CONTROL_AUTH_GOOGLE_ID
      secret: "" # env: BENEATH_CONTROL_AUTH_GOOGLE_SECRET

data:
  http_port: 5000 # env: BENEATH_DATA_HTTP_PORT
  grpc_port: 50051 # env: BENEATH_DATA_GRPC_PORT

  log:
    driver: "" # env: BENEATH_DATA_LOG_DRIVER
    # driver-specific settings...
  
  index:
    driver: "" # env: BENEATH_DATA_INDEX_DRIVER
    # driver-specific settings...
  
  warehouse:
    driver: "" # env: BENEATH_DATA_WAREHOUSE_DRIVER
    # driver-specific settings...

# MQ driver settings:
#   - pubsub:
#     project_id: ""
#     subscriber_id: ""
#     emulator_host: ""
#     topic_prefix: ""
#     subscription_prefix: ""
#
# Data driver settings:
#   - bigtable:
#     project_id: ""
#     instance_id: ""
#     emulator_host: ""
#   - bigquery:
#     project_id: ""
#     instances_dataset_id: ""
