apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "control.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "control.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "control.chart" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.com/health-checks: "true"
    # nginx.org/grpc-services: {{ include "control.fullname" . }}
    # nginx.org/websocket-services: {{ include "control.fullname" . }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - secretName: {{ include "control.name" . }}-tls
      hosts: 
      - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ include "control.fullname" . }}
          servicePort: 8080
