apiVersion: apps/v1
kind: Deployment
metadata:
  name: clock
  labels:
    app.kubernetes.io/name: clock
    app.kubernetes.io/instance: clock
    app.kubernetes.io/managed-by: Manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clock
      app.kubernetes.io/instance: clock
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clock
        app.kubernetes.io/instance: clock
    spec:
      containers:
      - name: clock
        image: gcr.io/beneath/clock:latest
        imagePullPolicy: Always
        env:
        - name: BENEATH_SECRET
          valueFrom:
            secretKeyRef:
              name: clock
              key: secret
