apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-frontend
  labels:
    app: web-frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web-frontend
        tier: frontend
    spec:
      containers:
        - name: web-frontend-server
          image: gcr.io/beneathcrypto/web-frontend:480c016e36804b04625203b329a0de06bf3800c0
          ports:
            - name: web-frontend-pt
              containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 250m
              memory: 250Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: web-frontend-pt
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: web-frontend-pt
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
  labels:
    app: web-frontend-service
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: web-frontend-pt
      protocol: TCP
  selector:
    app: web-frontend
    tier: frontend
