apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "web.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: web-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: web-port
        readinessProbe:
          httpGet:
            path: /healthz
            port: web-port
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        {{- if not (empty .Values.extraEnv) }}
        {{- toYaml .Values.extraEnv | nindent 8 }}
        {{- end }}
