apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cloudsql-proxy
spec:
  selector:
    matchLabels:
      name: cloudsql-proxy
  template:
    metadata:
      labels:
        name: cloudsql-proxy
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command: ["/cloud_sql_proxy",
                  "-instances=beneathcrypto:us-east1:beneath-network=tcp:0.0.0.0:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        ports:
        - containerPort: 5432
          hostPort: 5432
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
