apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lending-club-loans-enriched
spec:
  schedule: "1 9,13,17,21 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lending-club-loans-enriched
            image: gcr.io/beneath/lending-club-loans-enriched:latest
            env:
              - name: BENEATH_SECRET
                valueFrom:
                  secretKeyRef:
                    name: lending-club-loans-enriched-service-secret
                    key: secret
          restartPolicy: OnFailure
