apiVersion: apps/v1
kind: Deployment
metadata:
  name: lending-club-loans-enriched
  labels:
    app.kubernetes.io/name: lending-club-loans-enriched
    app.kubernetes.io/instance: lending-club-loans-enriched
    app.kubernetes.io/managed-by: Manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lending-club-loans-enriched
      app.kubernetes.io/instance: lending-club-loans-enriched
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lending-club-loans-enriched
        app.kubernetes.io/instance: lending-club-loans-enriched
    spec:
      containers:
      - name: lending-club-loans-enriched
        image: gcr.io/beneath/lending-club-loans-enriched:latest
        imagePullPolicy: Always
        env:
          - name: BENEATH_SECRET
            valueFrom:
              secretKeyRef:
                name: lending-club-loans
                key: secret