apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-wallstreetbets-sentiment
  labels:
    app.kubernetes.io/name: r-wallstreetbets-sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: r-wallstreetbets-sentiment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: r-wallstreetbets-sentiment
    spec:
      containers:
        - name: r-wallstreetbets-sentiment
          image: gcr.io/beneath/examples-wallstreetbets-sentiment:latest
          imagePullPolicy: Always
          args: ["run", "examples/wallstreetbets-analytics/predict-sentiment"]
          env:
            - name: BENEATH_SECRET
              valueFrom:
                secretKeyRef:
                  name: r-wallstreetbets-sentiment
                  key: beneath-secret
